name: Build release
on:
  release:
    types: [created]
jobs:
  static:
    name: Create release artifact (static)
    runs-on: ubuntu-latest
    container:
      image: alpine:3.13
    steps:
      - name: Checkout the repository
        uses: actions/checkout@master

      - name: Install system dependencies
        run: |
          apk add alpine-sdk hiredis-dev linux-headers \
              libunwind-dev xz-dev meson ninja cmake udev \
              xz libunwind-static

      - name: Download libfuse dependency
        run: |
          wget https://github.com/libfuse/libfuse/releases/download/fuse-3.10.2/fuse-3.10.2.tar.xz
          tar -xf fuse-3.10.2.tar.xz
 
      - name: Build static libfuse
        run: |
          cd fuse-3.10.2 
          mkdir build
          cd build
          meson .. --prefix /usr -Dudevrulesdir=/etc/udev/rules.d --default-library static
          ninja
          ninja install

      - name: Build production 0-db-fs
        run: |
          make production
          version=$(grep ZDBFS_VERSION src/zdbfs.h | awk '{ print $3 }' | sed s/'"'//g)
          cp zdbfs zdbfs-${version}-amd64-linux-static

      - name: Upload the artifacts
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: 'zdbfs-*-linux-static'

