name: Tests and Coverage
on: [push]

jobs:
  kernel:
    name: Kernel Build compare
    runs-on: ubuntu-20.04
    steps:
    - name: Prepare dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libfuse3-dev libhiredis-dev

    - name: Checkout code into the Go module directory
      uses: actions/checkout@v1

    - name: Build filesystem
      run: |
        make release

    - name: Run tests
      run: |
        sudo mkdir /mnt/zdbfs
        sudo ./zdbfs /mnt/zdbfs

