name: Tests and Coverage
on: [push]

jobs:
  kernel:
    name: Kernel Build compare
    runs-on: ubuntu-20.04
    steps:
    - name: Prepare dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libfuse3-dev libhiredis-dev redis-tools wget

    - name: Checkout code into the Go module directory
      uses: actions/checkout@v1

    - name: Build filesystem
      run: |
        make release

    - name: Build 0-db
      run: |
        git clone https://github.com/threefoldtech/0-db
        cd 0-db/libzdb && make release
        cd ../zdbd && make release

    - name: Run 0-db backend
      run: |
        cd 0-db/zdbd && ./zdb --mode seq --background

    - name: Create original namespaces
      run: |
        echo "NSNEW zdbfs-meta" | redis-cli -p 9900
        echo "NSNEW zdbfs-data" | redis-cli -p 9900
        echo "NSNEW zdbfs-temp" | redis-cli -p 9900
        echo "NSSET zdbfs-temp password hello" | redis-cli -p 9900
        echo "NSSET zdbfs-temp public 0" | redis-cli -p 9900

    - name: Run tests
      run: |
        sudo mkdir /mnt/zdbfs
        sudo chown runner /mnt/zdbfs
        ./zdbfs /mnt/zdbfs &

    - name: Wait for filesystem ready
      run: |
        while ! grep -q zdbfs /proc/mounts; do sleep 0.1; done

    - name: Download Linux Kernel
      run: |
        cd /tmp && wget https://cdn.kernel.org/pub/linux/kernel/v5.x/linux-5.9.13.tar.xz

    - name: Extract the kernel on zdbfs
      run: |
        sudo tar -xf /tmp/linux-5.9.13.tar.xz -C /mnt/zdbfs/

    - name: Build the kernel on zdbfs
      run: |
        sudo 'cd /mnt/zdbfs/linux-5.9.13 && KBUILD_BUILD_TIMESTAMP="Tue Dec 15 03:54:50 AM CET 2020" make defconfig'
        sudo 'cd /mnt/zdbfs/linux-5.9.13 && KBUILD_BUILD_TIMESTAMP="Tue Dec 15 03:54:50 AM CET 2020" make -j 8'

    - name: Extract the kernel on the root filesystem
      run: |
        tar -xf /tmp/linux-5.9.13.tar.xz -C /tmp/

    - name: Build the kernel on root filesystem
      run: |
        cd /tmp/linux-5.9.13
        KBUILD_BUILD_TIMESTAMP="Tue Dec 15 03:54:50 AM CET 2020" make defconfig
        KBUILD_BUILD_TIMESTAMP="Tue Dec 15 03:54:50 AM CET 2020" make -j 8

    - name: Compare builds
      run:
        sudo diff -qr -x tools -x x86 /opt/linux-5.9.13 /mnt/zdbfs/linux-5.9.13


